spring.application.name=guias
server.port=8080

spring.datasource.url=jdbc:oracle:thin:@sumativa1_high
spring.datasource.username=ADMIN
spring.datasource.password=qwer1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

oracle.net.tns_admin=/opt/oracle/wallet